[package]
name = "blitz"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = ">=2.6.3"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true