[package]
name = "atemu"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = ">=2.8.4"
openzeppelin = "0.19.0"
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true
