[package]
name = "atemu"
version = "0.1.0"
edition = "2023_01"

[dependencies]
starknet = ">=2.6.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true